sudo: required
services:
  - docker

before_install:
  - docker build -t rajesh1982002/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rajesh1982002/react-test npm test -- --coverage

after_success:
  - docker build -t rajesh1982002/multi-client ./client
  - docker build -t rajesh1982002/multi-nginx ./nginx
  - docker build -t rajesh1982002/multi-server ./server
  - docker build -t rajesh1982002/multi-worker ./worker



##  Now Login to Docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  ## Take those images and push into Dockhub.

  - docker push rajesh1982002/multi-client
  - docker push rajesh1982002/multi-nginx
  - docker push rajesh1982002/multi-server
  - docker push rajesh1982002/multi-worker

## 

deploy: 
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-dcoker
  env: MultiDcoker-env 
  bucket_name: elasticbeanstalk-us-east-1-900256733196
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

